const express=require('express')
const { addBook, getAllBook, getOneBook, addViewBook } = require('../controllers/book')
const {authenticate}=require('../middlewares/authenticate')
const {authorization}=require('../middlewares/authorization')
const router=express.Router()
router.post('/books',authenticate,authorization,addBook)
router.get('/books',getAllBook)
router.get('/books/:id',getOneBook)
router.patch('/books/addView/:id',addViewBook)
module.exports=router